name: flt_omi
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  logger: ^2.6.2
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0
  riverpod_annotation: ^4.0.0
  objectbox: ^4.0.3
  freezed_annotation: ^3.1.0
  lottie: ^3.3.2
  font_awesome_flutter: ^10.12.0
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^4.0.0+1
  objectbox_generator: ^4.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/welcome_text_animation.json
    - assets/images/
